# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddContactWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddNumber(object):
    def setupUi(self, DialogAddNumber):
        DialogAddNumber.setObjectName("DialogAddNumber")
        DialogAddNumber.resize(519, 341)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAddNumber)
        self.buttonBox.setGeometry(QtCore.QRect(20, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(DialogAddNumber)
        self.label.setGeometry(QtCore.QRect(80, 40, 111, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(DialogAddNumber)
        self.lineEdit.setGeometry(QtCore.QRect(190, 40, 151, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(DialogAddNumber)
        self.textEdit.setGeometry(QtCore.QRect(193, 80, 151, 87))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(DialogAddNumber)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 91, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(DialogAddNumber)
        self.buttonBox.accepted.connect(DialogAddNumber.accept)
        self.buttonBox.rejected.connect(DialogAddNumber.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAddNumber)

    def retranslateUi(self, DialogAddNumber):
        _translate = QtCore.QCoreApplication.translate
        DialogAddNumber.setWindowTitle(_translate("DialogAddNumber", "Dialog"))
        self.label.setText(_translate("DialogAddNumber", "Номер телефона"))
        self.textEdit.setHtml(_translate("DialogAddNumber", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("DialogAddNumber", "Комментарий"))
