# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 60, 351, 421))
        self.listWidget.setObjectName("listWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(450, 60, 301, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineSearchContact = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearchContact.setGeometry(QtCore.QRect(552, 441, 191, 31))
        self.lineSearchContact.setObjectName("lineSearchContact")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 450, 91, 20))
        self.label.setObjectName("label")
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setGeometry(QtCore.QRect(550, 480, 93, 28))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAll.setGeometry(QtCore.QRect(650, 480, 93, 28))
        self.pushButtonAll.setObjectName("pushButtonAll")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreateContact = QtWidgets.QAction(MainWindow)
        self.actionCreateContact.setObjectName("actionCreateContact")
        self.actionEditContact = QtWidgets.QAction(MainWindow)
        self.actionEditContact.setObjectName("actionEditContact")
        self.actionRemoveContact = QtWidgets.QAction(MainWindow)
        self.actionRemoveContact.setObjectName("actionRemoveContact")
        self.actionAppendNumber = QtWidgets.QAction(MainWindow)
        self.actionAppendNumber.setObjectName("actionAppendNumber")
        self.actionShowContacts = QtWidgets.QAction(MainWindow)
        self.actionShowContacts.setObjectName("actionShowContacts")
        self.actionEditNumber = QtWidgets.QAction(MainWindow)
        self.actionEditNumber.setObjectName("actionEditNumber")
        self.actionDeleteNumber = QtWidgets.QAction(MainWindow)
        self.actionDeleteNumber.setObjectName("actionDeleteNumber")
        self.actionAddNote = QtWidgets.QAction(MainWindow)
        self.actionAddNote.setObjectName("actionAddNote")
        self.menu.addAction(self.actionCreateContact)
        self.menu.addAction(self.actionEditContact)
        self.menu.addAction(self.actionRemoveContact)
        self.menu.addAction(self.actionAppendNumber)
        self.menu.addAction(self.actionShowContacts)
        self.menu_2.addAction(self.actionEditNumber)
        self.menu_2.addAction(self.actionDeleteNumber)
        self.menu_2.addAction(self.actionAddNote)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Найти контакт"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Найти "))
        self.pushButtonAll.setText(_translate("MainWindow", "Сброс"))
        self.menu.setTitle(_translate("MainWindow", "Контакт"))
        self.menu_2.setTitle(_translate("MainWindow", "Телефон"))
        self.actionCreateContact.setText(_translate("MainWindow", "Создать"))
        self.actionEditContact.setText(_translate("MainWindow", "Редактировать"))
        self.actionRemoveContact.setText(_translate("MainWindow", "Удалить"))
        self.actionAppendNumber.setText(_translate("MainWindow", "Добавить номер телефона"))
        self.actionShowContacts.setText(_translate("MainWindow", "Показать номера"))
        self.actionEditNumber.setText(_translate("MainWindow", "Редактировать "))
        self.actionDeleteNumber.setText(_translate("MainWindow", "Удалить "))
        self.actionAddNote.setText(_translate("MainWindow", "Добавить комментарий"))
